// Generated by gencpp from file cobot_pump_ros/checkItemAttached.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_CHECKITEMATTACHED_H
#define COBOT_PUMP_ROS_MESSAGE_CHECKITEMATTACHED_H

#include <ros/service_traits.h>


#include <cobot_pump_ros/checkItemAttachedRequest.h>
#include <cobot_pump_ros/checkItemAttachedResponse.h>


namespace cobot_pump_ros
{

struct checkItemAttached
{

typedef checkItemAttachedRequest Request;
typedef checkItemAttachedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct checkItemAttached
} // namespace cobot_pump_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cobot_pump_ros::checkItemAttached > {
  static const char* value()
  {
    return "247832619fa5dc1b609564c0b8dfd0c8";
  }

  static const char* value(const ::cobot_pump_ros::checkItemAttached&) { return value(); }
};

template<>
struct DataType< ::cobot_pump_ros::checkItemAttached > {
  static const char* value()
  {
    return "cobot_pump_ros/checkItemAttached";
  }

  static const char* value(const ::cobot_pump_ros::checkItemAttached&) { return value(); }
};


// service_traits::MD5Sum< ::cobot_pump_ros::checkItemAttachedRequest> should match
// service_traits::MD5Sum< ::cobot_pump_ros::checkItemAttached >
template<>
struct MD5Sum< ::cobot_pump_ros::checkItemAttachedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cobot_pump_ros::checkItemAttached >::value();
  }
  static const char* value(const ::cobot_pump_ros::checkItemAttachedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cobot_pump_ros::checkItemAttachedRequest> should match
// service_traits::DataType< ::cobot_pump_ros::checkItemAttached >
template<>
struct DataType< ::cobot_pump_ros::checkItemAttachedRequest>
{
  static const char* value()
  {
    return DataType< ::cobot_pump_ros::checkItemAttached >::value();
  }
  static const char* value(const ::cobot_pump_ros::checkItemAttachedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cobot_pump_ros::checkItemAttachedResponse> should match
// service_traits::MD5Sum< ::cobot_pump_ros::checkItemAttached >
template<>
struct MD5Sum< ::cobot_pump_ros::checkItemAttachedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cobot_pump_ros::checkItemAttached >::value();
  }
  static const char* value(const ::cobot_pump_ros::checkItemAttachedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cobot_pump_ros::checkItemAttachedResponse> should match
// service_traits::DataType< ::cobot_pump_ros::checkItemAttached >
template<>
struct DataType< ::cobot_pump_ros::checkItemAttachedResponse>
{
  static const char* value()
  {
    return DataType< ::cobot_pump_ros::checkItemAttached >::value();
  }
  static const char* value(const ::cobot_pump_ros::checkItemAttachedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_CHECKITEMATTACHED_H
