// Generated by gencpp from file cobot_pump_ros/dropItemResponse.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_DROPITEMRESPONSE_H
#define COBOT_PUMP_ROS_MESSAGE_DROPITEMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cobot_pump_ros
{
template <class ContainerAllocator>
struct dropItemResponse_
{
  typedef dropItemResponse_<ContainerAllocator> Type;

  dropItemResponse_()
    : success(false)  {
    }
  dropItemResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> const> ConstPtr;

}; // struct dropItemResponse_

typedef ::cobot_pump_ros::dropItemResponse_<std::allocator<void> > dropItemResponse;

typedef boost::shared_ptr< ::cobot_pump_ros::dropItemResponse > dropItemResponsePtr;
typedef boost::shared_ptr< ::cobot_pump_ros::dropItemResponse const> dropItemResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator1> & lhs, const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator1> & lhs, const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cobot_pump_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cobot_pump_ros/dropItemResponse";
  }

  static const char* value(const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dropItemResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cobot_pump_ros::dropItemResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cobot_pump_ros::dropItemResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_DROPITEMRESPONSE_H
