// Generated by gencpp from file cobot_pump_ros/dropItemRequest.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_DROPITEMREQUEST_H
#define COBOT_PUMP_ROS_MESSAGE_DROPITEMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cobot_pump_ros
{
template <class ContainerAllocator>
struct dropItemRequest_
{
  typedef dropItemRequest_<ContainerAllocator> Type;

  dropItemRequest_()
    : timeout_ms(0)  {
    }
  dropItemRequest_(const ContainerAllocator& _alloc)
    : timeout_ms(0)  {
  (void)_alloc;
    }



   typedef int64_t _timeout_ms_type;
  _timeout_ms_type timeout_ms;





  typedef boost::shared_ptr< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> const> ConstPtr;

}; // struct dropItemRequest_

typedef ::cobot_pump_ros::dropItemRequest_<std::allocator<void> > dropItemRequest;

typedef boost::shared_ptr< ::cobot_pump_ros::dropItemRequest > dropItemRequestPtr;
typedef boost::shared_ptr< ::cobot_pump_ros::dropItemRequest const> dropItemRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator1> & lhs, const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator2> & rhs)
{
  return lhs.timeout_ms == rhs.timeout_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator1> & lhs, const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cobot_pump_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a4f6fbef558cba8844dd1016bc02a88";
  }

  static const char* value(const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a4f6fbef558cba8ULL;
  static const uint64_t static_value2 = 0x844dd1016bc02a88ULL;
};

template<class ContainerAllocator>
struct DataType< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cobot_pump_ros/dropItemRequest";
  }

  static const char* value(const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 timeout_ms\n"
;
  }

  static const char* value(const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeout_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dropItemRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cobot_pump_ros::dropItemRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cobot_pump_ros::dropItemRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeout_ms: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timeout_ms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_DROPITEMREQUEST_H
