// Generated by gencpp from file cobot_pump_ros/dropItem.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_DROPITEM_H
#define COBOT_PUMP_ROS_MESSAGE_DROPITEM_H

#include <ros/service_traits.h>


#include <cobot_pump_ros/dropItemRequest.h>
#include <cobot_pump_ros/dropItemResponse.h>


namespace cobot_pump_ros
{

struct dropItem
{

typedef dropItemRequest Request;
typedef dropItemResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct dropItem
} // namespace cobot_pump_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cobot_pump_ros::dropItem > {
  static const char* value()
  {
    return "96b70f2966d4e8cb10a582cc9fbbdb44";
  }

  static const char* value(const ::cobot_pump_ros::dropItem&) { return value(); }
};

template<>
struct DataType< ::cobot_pump_ros::dropItem > {
  static const char* value()
  {
    return "cobot_pump_ros/dropItem";
  }

  static const char* value(const ::cobot_pump_ros::dropItem&) { return value(); }
};


// service_traits::MD5Sum< ::cobot_pump_ros::dropItemRequest> should match
// service_traits::MD5Sum< ::cobot_pump_ros::dropItem >
template<>
struct MD5Sum< ::cobot_pump_ros::dropItemRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cobot_pump_ros::dropItem >::value();
  }
  static const char* value(const ::cobot_pump_ros::dropItemRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cobot_pump_ros::dropItemRequest> should match
// service_traits::DataType< ::cobot_pump_ros::dropItem >
template<>
struct DataType< ::cobot_pump_ros::dropItemRequest>
{
  static const char* value()
  {
    return DataType< ::cobot_pump_ros::dropItem >::value();
  }
  static const char* value(const ::cobot_pump_ros::dropItemRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cobot_pump_ros::dropItemResponse> should match
// service_traits::MD5Sum< ::cobot_pump_ros::dropItem >
template<>
struct MD5Sum< ::cobot_pump_ros::dropItemResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cobot_pump_ros::dropItem >::value();
  }
  static const char* value(const ::cobot_pump_ros::dropItemResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cobot_pump_ros::dropItemResponse> should match
// service_traits::DataType< ::cobot_pump_ros::dropItem >
template<>
struct DataType< ::cobot_pump_ros::dropItemResponse>
{
  static const char* value()
  {
    return DataType< ::cobot_pump_ros::dropItem >::value();
  }
  static const char* value(const ::cobot_pump_ros::dropItemResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_DROPITEM_H
