// Generated by gencpp from file cobot_pump_ros/hci_action_srvResponse.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_HCI_ACTION_SRVRESPONSE_H
#define COBOT_PUMP_ROS_MESSAGE_HCI_ACTION_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cobot_pump_ros/waypoint.h>

namespace cobot_pump_ros
{
template <class ContainerAllocator>
struct hci_action_srvResponse_
{
  typedef hci_action_srvResponse_<ContainerAllocator> Type;

  hci_action_srvResponse_()
    : waypoints()  {
    }
  hci_action_srvResponse_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::cobot_pump_ros::waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cobot_pump_ros::waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct hci_action_srvResponse_

typedef ::cobot_pump_ros::hci_action_srvResponse_<std::allocator<void> > hci_action_srvResponse;

typedef boost::shared_ptr< ::cobot_pump_ros::hci_action_srvResponse > hci_action_srvResponsePtr;
typedef boost::shared_ptr< ::cobot_pump_ros::hci_action_srvResponse const> hci_action_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator1> & lhs, const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator1> & lhs, const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cobot_pump_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c700632b90a1c5ce1f9540e757918e84";
  }

  static const char* value(const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc700632b90a1c5ceULL;
  static const uint64_t static_value2 = 0x1f9540e757918e84ULL;
};

template<class ContainerAllocator>
struct DataType< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cobot_pump_ros/hci_action_srvResponse";
  }

  static const char* value(const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cobot_pump_ros/waypoint[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: cobot_pump_ros/waypoint\n"
"geometry_msgs/Pose pose\n"
"bool franka_gripper\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hci_action_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cobot_pump_ros::hci_action_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cobot_pump_ros::waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_HCI_ACTION_SRVRESPONSE_H
