// Generated by gencpp from file cobot_pump_ros/readState.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_READSTATE_H
#define COBOT_PUMP_ROS_MESSAGE_READSTATE_H

#include <ros/service_traits.h>


#include <cobot_pump_ros/readStateRequest.h>
#include <cobot_pump_ros/readStateResponse.h>


namespace cobot_pump_ros
{

struct readState
{

typedef readStateRequest Request;
typedef readStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct readState
} // namespace cobot_pump_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cobot_pump_ros::readState > {
  static const char* value()
  {
    return "247832619fa5dc1b609564c0b8dfd0c8";
  }

  static const char* value(const ::cobot_pump_ros::readState&) { return value(); }
};

template<>
struct DataType< ::cobot_pump_ros::readState > {
  static const char* value()
  {
    return "cobot_pump_ros/readState";
  }

  static const char* value(const ::cobot_pump_ros::readState&) { return value(); }
};


// service_traits::MD5Sum< ::cobot_pump_ros::readStateRequest> should match
// service_traits::MD5Sum< ::cobot_pump_ros::readState >
template<>
struct MD5Sum< ::cobot_pump_ros::readStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cobot_pump_ros::readState >::value();
  }
  static const char* value(const ::cobot_pump_ros::readStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cobot_pump_ros::readStateRequest> should match
// service_traits::DataType< ::cobot_pump_ros::readState >
template<>
struct DataType< ::cobot_pump_ros::readStateRequest>
{
  static const char* value()
  {
    return DataType< ::cobot_pump_ros::readState >::value();
  }
  static const char* value(const ::cobot_pump_ros::readStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cobot_pump_ros::readStateResponse> should match
// service_traits::MD5Sum< ::cobot_pump_ros::readState >
template<>
struct MD5Sum< ::cobot_pump_ros::readStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cobot_pump_ros::readState >::value();
  }
  static const char* value(const ::cobot_pump_ros::readStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cobot_pump_ros::readStateResponse> should match
// service_traits::DataType< ::cobot_pump_ros::readState >
template<>
struct DataType< ::cobot_pump_ros::readStateResponse>
{
  static const char* value()
  {
    return DataType< ::cobot_pump_ros::readState >::value();
  }
  static const char* value(const ::cobot_pump_ros::readStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_READSTATE_H
