// Generated by gencpp from file cobot_pump_ros/startPumpResponse.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_STARTPUMPRESPONSE_H
#define COBOT_PUMP_ROS_MESSAGE_STARTPUMPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cobot_pump_ros
{
template <class ContainerAllocator>
struct startPumpResponse_
{
  typedef startPumpResponse_<ContainerAllocator> Type;

  startPumpResponse_()
    : vacuumSuccess(false)  {
    }
  startPumpResponse_(const ContainerAllocator& _alloc)
    : vacuumSuccess(false)  {
  (void)_alloc;
    }



   typedef uint8_t _vacuumSuccess_type;
  _vacuumSuccess_type vacuumSuccess;





  typedef boost::shared_ptr< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> const> ConstPtr;

}; // struct startPumpResponse_

typedef ::cobot_pump_ros::startPumpResponse_<std::allocator<void> > startPumpResponse;

typedef boost::shared_ptr< ::cobot_pump_ros::startPumpResponse > startPumpResponsePtr;
typedef boost::shared_ptr< ::cobot_pump_ros::startPumpResponse const> startPumpResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator1> & lhs, const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator2> & rhs)
{
  return lhs.vacuumSuccess == rhs.vacuumSuccess;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator1> & lhs, const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cobot_pump_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0151a92fc5ce31e361ba616ee5a3609f";
  }

  static const char* value(const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0151a92fc5ce31e3ULL;
  static const uint64_t static_value2 = 0x61ba616ee5a3609fULL;
};

template<class ContainerAllocator>
struct DataType< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cobot_pump_ros/startPumpResponse";
  }

  static const char* value(const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool vacuumSuccess\n"
;
  }

  static const char* value(const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vacuumSuccess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct startPumpResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cobot_pump_ros::startPumpResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cobot_pump_ros::startPumpResponse_<ContainerAllocator>& v)
  {
    s << indent << "vacuumSuccess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vacuumSuccess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_STARTPUMPRESPONSE_H
