// Generated by gencpp from file cobot_pump_ros/stopPumpRequest.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_STOPPUMPREQUEST_H
#define COBOT_PUMP_ROS_MESSAGE_STOPPUMPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cobot_pump_ros
{
template <class ContainerAllocator>
struct stopPumpRequest_
{
  typedef stopPumpRequest_<ContainerAllocator> Type;

  stopPumpRequest_()
    {
    }
  stopPumpRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> const> ConstPtr;

}; // struct stopPumpRequest_

typedef ::cobot_pump_ros::stopPumpRequest_<std::allocator<void> > stopPumpRequest;

typedef boost::shared_ptr< ::cobot_pump_ros::stopPumpRequest > stopPumpRequestPtr;
typedef boost::shared_ptr< ::cobot_pump_ros::stopPumpRequest const> stopPumpRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace cobot_pump_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cobot_pump_ros/stopPumpRequest";
  }

  static const char* value(const ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stopPumpRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cobot_pump_ros::stopPumpRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_STOPPUMPREQUEST_H
