// Generated by gencpp from file cobot_pump_ros/stopPump.msg
// DO NOT EDIT!


#ifndef COBOT_PUMP_ROS_MESSAGE_STOPPUMP_H
#define COBOT_PUMP_ROS_MESSAGE_STOPPUMP_H

#include <ros/service_traits.h>


#include <cobot_pump_ros/stopPumpRequest.h>
#include <cobot_pump_ros/stopPumpResponse.h>


namespace cobot_pump_ros
{

struct stopPump
{

typedef stopPumpRequest Request;
typedef stopPumpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stopPump
} // namespace cobot_pump_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cobot_pump_ros::stopPump > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::cobot_pump_ros::stopPump&) { return value(); }
};

template<>
struct DataType< ::cobot_pump_ros::stopPump > {
  static const char* value()
  {
    return "cobot_pump_ros/stopPump";
  }

  static const char* value(const ::cobot_pump_ros::stopPump&) { return value(); }
};


// service_traits::MD5Sum< ::cobot_pump_ros::stopPumpRequest> should match
// service_traits::MD5Sum< ::cobot_pump_ros::stopPump >
template<>
struct MD5Sum< ::cobot_pump_ros::stopPumpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cobot_pump_ros::stopPump >::value();
  }
  static const char* value(const ::cobot_pump_ros::stopPumpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cobot_pump_ros::stopPumpRequest> should match
// service_traits::DataType< ::cobot_pump_ros::stopPump >
template<>
struct DataType< ::cobot_pump_ros::stopPumpRequest>
{
  static const char* value()
  {
    return DataType< ::cobot_pump_ros::stopPump >::value();
  }
  static const char* value(const ::cobot_pump_ros::stopPumpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cobot_pump_ros::stopPumpResponse> should match
// service_traits::MD5Sum< ::cobot_pump_ros::stopPump >
template<>
struct MD5Sum< ::cobot_pump_ros::stopPumpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cobot_pump_ros::stopPump >::value();
  }
  static const char* value(const ::cobot_pump_ros::stopPumpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cobot_pump_ros::stopPumpResponse> should match
// service_traits::DataType< ::cobot_pump_ros::stopPump >
template<>
struct DataType< ::cobot_pump_ros::stopPumpResponse>
{
  static const char* value()
  {
    return DataType< ::cobot_pump_ros::stopPump >::value();
  }
  static const char* value(const ::cobot_pump_ros::stopPumpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COBOT_PUMP_ROS_MESSAGE_STOPPUMP_H
